name: LeetCode Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Create directory
      run: |
        mkdir -p .github/workflows
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install leetcode-cli
        
    - name: Sync LeetCode solutions
      env:
        LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}
      run: |
        leetcode-cli sync
        git add .
        git commit -m "Update LeetCode solutions"
        git push
